version: "3.9"

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@host.docker.internal:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: USR_MS
      SPRING_DATASOURCE_PASSWORD: USR_MS_PWD
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

  lab-service:
    build:
      context: ./lab-service
      dockerfile: Dockerfile
    container_name: lab-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@host.docker.internal:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: LAB_MS
      SPRING_DATASOURCE_PASSWORD: LAB_MS_PWD
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
    depends_on:
      - user-service
